apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-server.fullname" . }}-config
  labels:
    {{- include "mcp-server.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.config | toJson | nindent 4 }} 